export const IPC_CHANNELS = {
  getBootstrapState: "pho-code:v1:getBootstrapState",
  pickWorkspace: "pho-code:v1:pickWorkspace",
  openRecentWorkspace: "pho-code:v1:openRecentWorkspace",
  listWorkspaceSessions: "pho-code:v1:listWorkspaceSessions",
  createSession: "pho-code:v1:createSession",
  openSession: "pho-code:v1:openSession",
  sendPrompt: "pho-code:v1:sendPrompt",
  abortRun: "pho-code:v1:abortRun",
  setSessionModel: "pho-code:v1:setSessionModel",
  setThinkingLevel: "pho-code:v1:setThinkingLevel",
  resolveHostDialog: "pho-code:v1:resolveHostDialog",
  getSettings: "pho-code:v1:getSettings",
  updateAppearanceSettings: "pho-code:v1:updateAppearanceSettings",
  updatePermissionSettings: "pho-code:v1:updatePermissionSettings",
  listCredentialProviders: "pho-code:v1:listCredentialProviders",
  importProviderApiKey: "pho-code:v1:importProviderApiKey",
  event: "pho-code:v1:event",
} as const;
