export { PROTOCOL_COMMANDS, PROTOCOL_VERSION, INTENDED_PI_SDK, PINNED_ELECTRON, isSupportedProtocolVersion } from "./version";
export type { ProtocolCommandName, ProtocolVersion } from "./version";

export { createHarnessError, failCommand, HARNESS_ERROR_CODES, isHarnessError } from "./errors";
export type { HarnessError } from "./errors";

export { commandFail, commandOk, isCommandResult, unwrapCommandResult } from "./command-result";
export type { CommandResult } from "./command-result";

export {
  appendThinkingDelta,
  applyLiveRunDelta,
  applyRuntimeEvent,
  applyRuntimeEventToCache,
  emptyConversationCache,
  emptyConversationState,
  eventSessionKey,
  isLiveRunDeltaType,
  isProcessScopedEventType,
  mergeLiveRun,
  RUNTIME_EVENT_TYPES,
  runtimeEventUpdatesSessionList,
  upsertToolWork,
} from "./events";
export type {
  ConversationCacheState,
  ConversationViewState,
  ExtensionDialogSettledPayload,
  RuntimeEvent,
  RuntimeEventEnvelope,
  RuntimeEventType,
  RunFailedPayload,
  SessionRemovedPayload,
  TextDeltaPayload,
  ThinkingDeltaPayload,
  ToolEventPayload,
  Unsubscribe,
} from "./events";

export type {
  BootstrapCapabilities,
  BootstrapMilestone,
  BootstrapState,
  BootstrapVersions,
  PiRuntimeStatusSnapshot,
} from "./bootstrap";

export type {
  CancelProviderLoginInput,
  CredentialProviderSummary,
  ImportProviderApiKeyInput,
  ImportProviderApiKeyResult,
  LogoutProviderInput,
  OpenProviderAuthLinkInput,
  ProviderAccountSummary,
  ProviderAccountsResult,
  ProviderAuthDeviceCode,
  ProviderAuthFlowPhase,
  ProviderAuthFlowSnapshot,
  ProviderAuthLink,
  ProviderAuthMethod,
  ProviderAuthPrompt,
  ProviderAuthPromptKind,
  ProviderAuthSelectOption,
  ProviderDisclosureKey,
  RespondProviderAuthPromptInput,
  StartProviderLoginInput,
} from "./credentials";
export {
  idleProviderAccountsResult,
  isProviderAuthFlowPhase,
  isProviderAuthMethod,
  MAX_PROVIDER_AUTH_MESSAGE,
  MAX_PROVIDER_AUTH_OPTIONS,
  MAX_PROVIDER_AUTH_PROGRESS,
  MAX_PROVIDER_AUTH_VALUE,
  PROVIDER_AUTH_FLOW_PHASES,
  PROVIDER_AUTH_METHODS,
  PROVIDER_AUTH_PROMPT_KINDS,
  PROVIDER_DISCLOSURE_KEYS,
  providerDisclosureCopy,
} from "./credentials";

export { hostnameFromHttpUrl, isSafeHttpUrl } from "./http-url";

export type { DesktopBridge } from "./bridge";

export {
  blockingReviewStatuses,
  CHANGE_DIFF_LINE_KINDS,
  CHANGE_FILE_VERSIONS,
  CHANGE_KINDS,
  CHANGE_CONTENT_HASH_PATTERN,
  CHANGE_LEDGER_DISCLOSURE,
  CHANGE_LIMITATIONS,
  CHANGE_LINE_ENDINGS,
  CHANGE_REVIEW_COPY,
  CHANGE_SCOPE_FIELDS,
  CHANGE_UNREADABLE_RUN_ID,
  CHANGE_UNTRACKED_PATH_PREFIX,
  changeScopeEquals,
  changeScopeId,
  DEFAULT_CHANGE_CONTEXT_LINES,
  emptyChangeReviews,
  formatChangeDiffCursor,
  formatChangedFileCount,
  formatChangeFileViewCursor,
  latestChangeReview,
  hasDisallowedControlChars,
  isChangeContentHash,
  isChangeFileVersion,
  isChangeKind,
  isChangeLimitation,
  isChangeScope,
  isPersistableRelativePath,
  isReviewStatus,
  isUndoAction,
  isUntrackedChangePath,
  MAX_CHANGE_BLOB_BYTES_PER_RUN,
  MAX_CHANGE_CONTEXT_LINES,
  MAX_CHANGE_CURSOR_CHARS,
  MAX_CHANGE_DIFF_CHARS,
  MAX_CHANGE_DIFF_HUNKS_PER_PAGE,
  MAX_CHANGE_DIFF_INPUT_LINES,
  MAX_CHANGE_DIFF_LINES_PER_PAGE,
  MAX_CHANGE_DIFF_PATCH_CHARS,
  MAX_CHANGE_FILE_VIEW_CHARS,
  MAX_CHANGE_FILES_ON_SUMMARY,
  MAX_CHANGE_LEDGER_BYTES,
  MAX_CHANGE_LEDGER_STRING_CHARS,
  MAX_CHANGE_MANIFEST_BYTES,
  MAX_CHANGE_OPERATIONS_PER_RUN,
  MAX_CHANGE_PATHS_PER_RUN,
  MAX_CHANGE_PREVIEW_TOKEN_CHARS,
  MAX_CHANGE_RELATIVE_PATH_CHARS,
  MAX_CHANGE_REVIEWS_ON_SNAPSHOT,
  MAX_CHANGE_SCOPE_ID_CHARS,
  MAX_CHANGE_SNAPSHOT_BYTES,
  MAX_CHANGE_TOOL_CALL_ID_CHARS,
  parseChangeDiffCursor,
  parseChangeFileViewCursor,
  requireChangeContextLines,
  requireChangePreviewToken,
  requireChangeRelativePath,
  requireChangeRelativePaths,
  requireChangeRevision,
  requireChangeScope,
  REVIEW_STATUSES,
  UNDO_ACTIONS,
  reviewFileCount,
  reviewSummaryForToolCall,
} from "./change-review";
export type {
  ApproveChangesInput,
  ApplyUndoChangesInput,
  ChangeDiffCursor,
  ChangeDiffHunk,
  ChangeDiffLine,
  ChangeDiffLineKind,
  ChangeDiffPage,
  ChangeFileVersion,
  ChangeFileViewCursor,
  ChangeFileViewPage,
  ChangeKind,
  ChangeLimitation,
  ChangeLineEnding,
  ChangeReviewSetSnapshot,
  ChangeReviewSetSummary,
  ChangeScope,
  FileChangeSummary,
  GetChangeDiffInput,
  GetChangeFileViewInput,
  GetChangeReviewSetInput,
  PrepareUndoChangesInput,
  ReviewStatus,
  UndoAction,
  UndoPreview,
} from "./change-review";

export {
  agentsSectionId,
  DEFAULT_CONTEXT_PROMPT_PREAMBLE,
  emptySessionContextPrompt,
  isContextPromptSectionKind,
  MAX_CONTEXT_PROMPT_PREAMBLE_CHARS,
  parseToolSectionId,
  PI_DOCS_SECTION_BODY,
  PI_DOCS_SECTION_ID,
  toolSectionId,
  CONTEXT_PROMPT_SECTION_KINDS,
} from "./context-prompt";
export type {
  ContextPromptSection,
  ContextPromptSectionKind,
  SessionContextPrompt,
  UpdateSessionContextPromptInput,
} from "./context-prompt";

export {
  extractAtMentionPaths,
  findCompletedAtMentions,
  formatAtMentionToken,
} from "./at-mention";
export type { CompletedAtMention } from "./at-mention";

export {
  DEFAULT_WORKSPACE_REFERENCE_LIMIT,
  isWorkspaceReferenceKind,
  isWorkspaceReferenceToken,
  LOCAL_RETRIEVAL_STATUSES,
  MAX_WORKSPACE_REFERENCE_QUERY,
  MAX_WORKSPACE_REFERENCE_RESULTS,
  MAX_WORKSPACE_REFERENCES_PER_PROMPT,
  WORKSPACE_REFERENCE_KINDS,
} from "./retrieval";
export type {
  LocalRetrievalStatus,
  PathSuggestion,
  SearchWorkspaceReferencesInput,
  SearchWorkspaceReferencesResult,
  WorkspaceReferenceKind,
  WorkspaceReferenceToken,
} from "./retrieval";

export {
  isWebSearchProvider,
  isWebSourceProvider,
  isWebSourceRecord,
  MAX_WEB_CONCURRENT_REQUESTS,
  MAX_WEB_EXTRACTED_CHARS,
  MAX_WEB_REDIRECTS,
  MAX_WEB_RESPONSE_BYTES,
  MAX_WEB_SEARCH_QUERY,
  MAX_WEB_SEARCH_RESULTS,
  WEB_REQUEST_TIMEOUT_MS,
  WEB_SEARCH_PROVIDERS,
  WEB_SOURCE_PROVIDERS,
} from "./web";
export type { WebSearchProvider, WebSourceProvider, WebSourceRecord } from "./web";

export {
  emptyGitHubMcpSettingsSnapshot,
  GITHUB_MCP_AUTH_METHODS,
  GITHUB_MCP_DISCLOSURE,
  GITHUB_MCP_DISCLOSURE_ITEMS,
  GITHUB_MCP_FEATURE_ID,
  GITHUB_MCP_SECRET_STORE_NOTICE,
  GITHUB_MCP_STATUSES,
  GITHUB_MCP_TOOL_PREFIX,
  GITHUB_MCP_TRUST_NOTICE,
  githubMcpSecretStoreNotice,
  githubMcpStatusLabel,
  isGitHubMcpStatus,
  MAX_GITHUB_MCP_ERROR_CHARS,
  MAX_GITHUB_MCP_LOGIN_CHARS,
  MAX_GITHUB_PAT_CHARS,
} from "./github-mcp";
export type {
  GitHubMcpAccountSummary,
  GitHubMcpAuthMethod,
  GitHubMcpSettingsSnapshot,
  GitHubMcpStatus,
  ImportGitHubPatInput,
  ImportGitHubPatResult,
  UpdateGitHubMcpSettingsInput,
} from "./github-mcp";

export {
  emptySandboxSettingsSnapshot,
  isSandboxBashToolName,
  isSandboxNetworkMode,
  isSandboxStatus,
  isSandboxStatusReason,
  MAX_SANDBOX_ALLOWED_DOMAINS,
  MAX_SANDBOX_DOMAIN_CHARS,
  MAX_SANDBOX_PATH_CHARS,
  MAX_SANDBOX_PATH_LIST,
  parseSandboxAllowedDomains,
  parseSandboxDomain,
  parseSandboxPathEntry,
  parseSandboxPathList,
  parseSandboxSettingsPatch,
  SANDBOX_BASH_TOOL_NAMES,
  SANDBOX_DISCLOSURE,
  SANDBOX_NETWORK_MODES,
  SANDBOX_STATUS_REASONS,
  SANDBOX_STATUSES,
  sandboxBashWasWrapped,
  sandboxStatusLabel,
  sandboxStatusReasonLabel,
} from "./sandbox";
export type {
  SandboxBashToolName,
  SandboxNetworkMode,
  SandboxSettingsSnapshot,
  SandboxStatus,
  SandboxStatusReason,
  UpdateSandboxSettingsInput,
} from "./sandbox";

export {
  APPEARANCE_MODES,
  APPEARANCE_PALETTES,
  clampChatFontSize,
  clampGlassStrength,
  clampUiFontSize,
  coerceAppearance,
  DEFAULT_CHAT_FONT_SIZE,
  DEFAULT_GLASS_ENABLED,
  DEFAULT_GLASS_STRENGTH,
  DEFAULT_UI_FONT_SIZE,
  emptyAppearanceSettings,
  emptySettingsSnapshot,
  glassCssTokens,
  isAppearanceMode,
  isAppearancePalette,
  isChatFontSize,
  isGlassStrength,
  isManagedPermissionProfileId,
  isUiFontSize,
  MAX_CHAT_FONT_SIZE,
  MAX_GLASS_STRENGTH,
  MAX_UI_FONT_SIZE,
  MIN_CHAT_FONT_SIZE,
  MIN_GLASS_STRENGTH,
  MIN_UI_FONT_SIZE,
  nativeThemeSourceForAppearance,
  paletteSupportsMode,
  PERMISSION_PROFILE_IDS,
  resolveAppearanceMode,
  supportedAppearanceModes,
  windowBackgroundForAppearance,
} from "./settings";
export type {
  AppearanceMode,
  AppearancePalette,
  AppearanceSettings,
  HarnessSettingsSnapshot,
  ManagedPermissionProfileId,
  PermissionProfileId,
  PermissionSettings,
  PermissionStatusPayload,
  ResolvedAppearance,
  UpdateAppearanceSettingsInput,
  UpdatePermissionSettingsInput,
} from "./settings";

export {
  availableSlashSkills,
  emptySkillSettingsSnapshot,
  extractSkillTokens,
  EXTERNAL_SKILL_SOURCE_IDS,
  findCompletedSkillTokens,
  formatSkillToken,
  isExternalSkillSourceId,
  isSkillCompatibility,
  isSkillSourceId,
  MAX_SKILL_DESCRIPTION_CHARS,
  SKILL_BODY_CLOSE,
  SKILL_BODY_OPEN,
  SKILL_COMPATIBILITY_STATES,
  SKILL_SOURCE_IDS,
  SKILL_SOURCE_LABELS,
  SKILL_SOURCE_ROOT_LABELS,
  SKILL_TRUST_NOTICE,
  skillNeedsCompatibilityNotice,
  sourceCompatibilityWarnings,
  stripExpandedSkillBodies,
  wrapSkillBody,
} from "./skills";
export type {
  CompletedSkillToken,
  ExternalSkillSourceId,
  SkillCompatibility,
  SkillInventoryEntry,
  SkillSettingsSnapshot,
  SkillShadowRef,
  SkillSourceId,
  SkillSourceSummary,
  UpdateSkillSourceSettingsInput,
} from "./skills";

export {
  IMAGE_MIME_TYPES,
  MAX_IMAGE_PREVIEW_DIMENSION,
  MAX_PREPARED_IMAGE_DIMENSION,
  MAX_PREPARED_IMAGES,
  MAX_QUEUE_MESSAGE_PREVIEW,
  MAX_SOURCE_IMAGE_BYTES,
  isImageMimeType,
} from "./attachments";
export type {
  ImageMimeType,
  PasteImagesInput,
  PastedImageBytes,
  PickImagesInput,
  PickImagesResult,
  PrepareImageInput,
  PreparedImageSummary,
  RemovePreparedImageInput,
} from "./attachments";

export { emptyQueueState, idleRunState, isQueueMode, MAX_ASSISTANT_REWRITE_CHARS, QUEUE_MODES } from "./conversation";
export type {
  AbortRunInput,
  ContextUsageSummary,
  CreateSessionInput,
  ListWorkspaceSessionsInput,
  OpenRecentWorkspaceInput,
  OpenSessionInput,
  PromptAdmission,
  QueueAdmission,
  QueueFollowUpInput,
  QueueMessagePreview,
  QueueMode,
  ReorderRecentWorkspacesInput,
  RewriteAssistantOutputInput,
  RunState,
  RunStatus,
  RunWorkEntry,
  SendPromptInput,
  SessionQueueState,
  SessionSnapshot,
  SessionUsageSummary,
  SetSessionModelInput,
  SetThinkingLevelInput,
  SteerRunInput,
  ToolActivity,
  ToolStatus,
  TranscriptBlock,
  TranscriptImageBlock,
  TranscriptMessage,
  TranscriptRole,
  TranscriptTextBlock,
  TranscriptThinkingBlock,
  TranscriptToolBlock,
} from "./conversation";

export {
  activityRank,
  compareSessionActivity,
  isSessionActivityPhase,
  isSessionCatalogScope,
  isSessionKey,
  isSessionOutcome,
  parseSessionKeyId,
  requireMatchingSessionKey,
  SESSION_ACTIVITY_PHASES,
  SESSION_CATALOG_SCOPES,
  SESSION_OUTCOMES,
  sessionActivityPhase,
  sessionKeyEquals,
  sessionKeyId,
  visibleActivityPhase,
} from "./session-lifecycle";
export type {
  ArchiveSessionInput,
  GetSessionSnapshotInput,
  ListSessionCatalogInput,
  PrepareRemoveArchivedSessionsInput,
  PrepareRemoveArchivedSessionsResult,
  PrepareRemoveProjectInput,
  PrepareRemoveProjectResult,
  PrepareRemoveSessionInput,
  PrepareRemoveSessionResult,
  RemoveArchivedSessionsInput,
  RemoveArchivedSessionsResult,
  RemoveProjectInput,
  RemoveProjectResult,
  RemoveSessionInput,
  RemoveSessionResult,
  RestoreSessionInput,
  SessionActivityPhase,
  SessionActivitySummary,
  SessionCatalogEntry,
  SessionCatalogScope,
  SessionKey,
  SessionOutcome,
} from "./session-lifecycle";

export {
  emptyFeatureSnapshot,
  FEATURE_TRUST_NOTICE,
} from "./resources";
export type {
  ExtensionNotification,
  FeatureSnapshot,
  FeatureStatus,
  HarnessFeatureSummary,
  HostDialogKind,
  HostDialogRequest,
  ResolveHostDialogInput,
  ResourceDiagnostic,
  ResourceDiagnosticType,
} from "./resources";

export {
  ASK_USER_MAX_HEADER_CHARS,
  ASK_USER_MAX_LABEL_CHARS,
  ASK_USER_MAX_OPTIONS,
  ASK_USER_MAX_QUESTIONS,
  ASK_USER_MIN_OPTIONS,
  ASK_USER_OPTION_LETTERS,
  ASK_USER_QUESTION_TOOL_NAME,
  ASK_USER_RESERVED_LABELS,
  ASK_USER_TEXT_FIELD_MAX_BYTES,
  PLAN_DOCUMENT_MAX_BYTES,
  PLAN_TODO_MAX_CONTENT_CHARS,
  PLAN_TODO_MAX_ITEMS,
  PLAN_TODO_STATUSES,
  SESSION_AGENT_MODES,
  TODO_TOOL_NAME,
  UPDATE_PLAN_DOCUMENT_TOOL_NAME,
  EXECUTE_PLAN_TOOL_NAME,
  askUserOptionLetter,
  completedPlanTodoCount,
  emptySessionPlanSnapshot,
  inProgressPlanTodo,
  isAskUserAnswer,
  isAskUserAnswerKind,
  isAskUserErrorCode,
  isAskUserOption,
  isAskUserQuestion,
  isPlanTodoItem,
  isPlanTodoStatus,
  isSessionAgentMode,
  parseAskUserAnswers,
  parseAskUserQuestions,
  parsePlanTodoList,
  parsePlanTodosFromToolPreview,
  planDocumentTooLarge,
  withLivePlanTodos,
  remainingPlanTodoCount,
  utf8ByteLength,
} from "./plan-agent";
export type {
  AskUserAnswer,
  AskUserAnswerKind,
  AskUserErrorCode,
  AskUserOption,
  AskUserOptionLetter,
  AskUserQuestion,
  AskUserQuestionnaireDetails,
  AskUserReservedLabel,
  ExecuteSessionPlanInput,
  PlanTodoErrorCode,
  PlanTodoItem,
  PlanTodoStatus,
  SessionAgentMode,
  SessionPlanSnapshot,
  SetSessionModeInput,
  UpdateSessionPlanDocumentInput,
} from "./plan-agent";

export { isThinkingLevel, THINKING_LEVELS } from "./workspace";
export type {
  ModelCostRatesSummary,
  ModelSummary,
  RecentWorkspaceRecord,
  SessionSummary,
  ThinkingLevel,
  WorkspaceSnapshot,
  WorkspaceSummary,
} from "./workspace";

export {
  assertJsonSafe,
  compareNodeVersions,
  isJsonSafeValue,
  jsonRoundTrip,
  nodeVersionMeetsMinimum,
  parseNodeVersion,
} from "./json";
export * from "@pho-agent/protocol";
