const DENY_PERMANENT_REMOVAL = {
  action: "deny",
  reason: "Permanent removal is unavailable. Use the move_to_trash tool.",
} as const;

const DENY_PRIVILEGE = {
  action: "deny",
  reason: "Privilege escalation is denied.",
} as const;

const DENY_DESTRUCTIVE_GIT = {
  action: "deny",
  reason: "Destructive git history or worktree changes are denied.",
} as const;

const PERMANENT_REMOVAL_BASH_RULES = {
  "find * -delete": DENY_PERMANENT_REMOVAL,
  "find * -delete *": DENY_PERMANENT_REMOVAL,
  "find * -exec *": DENY_PERMANENT_REMOVAL,
  "find * -execdir *": DENY_PERMANENT_REMOVAL,
  rm: DENY_PERMANENT_REMOVAL,
  "rm *": DENY_PERMANENT_REMOVAL,
  unlink: DENY_PERMANENT_REMOVAL,
  "unlink *": DENY_PERMANENT_REMOVAL,
  rmdir: DENY_PERMANENT_REMOVAL,
  "rmdir *": DENY_PERMANENT_REMOVAL,
  shred: DENY_PERMANENT_REMOVAL,
  "shred *": DENY_PERMANENT_REMOVAL,
} as const;

/** Harness tools that are themselves the owner prompt; they must never open a permission dock. */
export const HARNESS_ALWAYS_ALLOW_PERMISSION = {
  ask_user_question: "allow",
  update_plan_document: "allow",
  todo: "allow",
  execute_plan: "allow",
} as const;

/** Managed profiles let search through; only fetch asks (public HTTP GET). */
export const MANAGED_WEB_PERMISSION = {
  web_search: "allow",
  fetch_content: "ask",
} as const;

export const GUARDED_PERMISSION = {
  "*": "ask",
  path: {
    "*": "ask",
    "*.env": "deny",
    "*.env.*": "deny",
    "*.env.example": "ask",
    "~/.ssh/*": "deny",
    "/dev/null": "allow",
  },
  external_directory: "ask",
  bash: {
    "*": "ask",
    ...PERMANENT_REMOVAL_BASH_RULES,
  },
  ...HARNESS_ALWAYS_ALLOW_PERMISSION,
  ...MANAGED_WEB_PERMISSION,
} as const;

export const BALANCED_PERMISSION = {
  "*": "ask",
  path: {
    "*": "allow",
    "*.env": "deny",
    "*.env.*": "deny",
    "*.env.example": "allow",
    "~/.ssh/*": "deny",
    "/dev/null": "allow",
  },
  read: "allow",
  find: "allow",
  grep: "allow",
  ls: "allow",
  write: "ask",
  edit: "ask",
  bash: {
    "*": "ask",
    ...PERMANENT_REMOVAL_BASH_RULES,
  },
  skill: "ask",
  mcp: "ask",
  external_directory: "ask",
  ...HARNESS_ALWAYS_ALLOW_PERMISSION,
  ...MANAGED_WEB_PERMISSION,
} as const;

/**
 * Internal `developer` policy key for permission-system 24.0.0.
 * Owner-facing Settings labels this as “with great power comes great responsibility”.
 * Object insertion order is significant: last matching rule wins.
 */
export const DEVELOPER_PERMISSION = {
  "*": "ask",
  path: {
    "*": "allow",
    "*.env": "deny",
    "*.env.*": "deny",
    "*.env.example": "allow",
    "~/.ssh/*": "deny",
    "~/.gnupg/*": "deny",
    "~/.aws/*": "deny",
    "~/.config/gcloud/*": "deny",
    "~/.azure/*": "deny",
    "~/.kube/*": "deny",
    "~/.netrc": "deny",
    "~/.npmrc": "deny",
    "~/.docker/config.json": "deny",
    "~/.config/gh/hosts.yml": "deny",
    "~/Library/Keychains/*": "deny",
    "~/Library/Cookies/*": "deny",
    "~/Library/Application Support/Google/Chrome/*Cookies": "deny",
    "~/Library/Application Support/Google/Chrome/*Login Data": "deny",
    "~/.mozilla/firefox/*cookies.sqlite": "deny",
    "id_rsa": "deny",
    "id_ed25519": "deny",
    "id_ecdsa": "deny",
    "*.pem": "deny",
    "*.key": "deny",
    "/dev/null": "allow",
  },
  read: "allow",
  find: "allow",
  grep: "allow",
  ls: "allow",
  ...MANAGED_WEB_PERMISSION,
  write: "allow",
  edit: "allow",
  move_to_trash: "allow",
  skill: "ask",
  mcp: "ask",
  external_directory: "ask",
  bash: {
    "*": "ask",
    pwd: "allow",
    cd: "allow",
    "cd *": "allow",
    ls: "allow",
    "ls *": "allow",
    rg: "ask",
    "rg *": "ask",
    grep: "ask",
    "grep *": "ask",
    find: "ask",
    "find *": "ask",
    head: "allow",
    "head *": "allow",
    tail: "allow",
    "tail *": "allow",
    wc: "allow",
    "wc *": "allow",
    file: "allow",
    "file *": "allow",
    "sed -n": "allow",
    "sed -n *": "allow",
    "git *": "ask",
    "git status": "allow",
    "git status *": "allow",
    "git diff": "allow",
    "git diff *": "allow",
    "git log": "allow",
    "git log *": "allow",
    "git show": "allow",
    "git show *": "allow",
    "git diff *--ext-diff*": "ask",
    "git diff *--textconv*": "ask",
    "git log *--ext-diff*": "ask",
    "git log *--textconv*": "ask",
    "git show *--ext-diff*": "ask",
    "git show *--textconv*": "ask",
    "git rev-parse": "allow",
    "git rev-parse *": "allow",
    "git branch": "allow",
    "git branch -a": "allow",
    "git branch -v": "allow",
    "git branch --list": "allow",
    "git branch --show-current": "allow",
    "bun run typecheck": "allow",
    "bun run lint": "allow",
    "bun test": "allow",
    "bun test *": "allow",
    "bun run test": "allow",
    "bun run test:desktop": "allow",
    "bun run build": "allow",
    "npm test": "allow",
    "npm test *": "allow",
    "npm run test": "allow",
    "npm run lint": "allow",
    "npm run typecheck": "allow",
    "npm run build": "allow",
    "pnpm test": "allow",
    "pnpm test *": "allow",
    "pnpm run test": "allow",
    "pnpm run lint": "allow",
    "pnpm run typecheck": "allow",
    "pnpm run build": "allow",
    ...PERMANENT_REMOVAL_BASH_RULES,
    sudo: DENY_PRIVILEGE,
    "sudo *": DENY_PRIVILEGE,
    doas: DENY_PRIVILEGE,
    "doas *": DENY_PRIVILEGE,
    "git clean": DENY_DESTRUCTIVE_GIT,
    "git clean *": DENY_DESTRUCTIVE_GIT,
    "git reset --hard": DENY_DESTRUCTIVE_GIT,
    "git reset --hard *": DENY_DESTRUCTIVE_GIT,
    "git checkout -f": DENY_DESTRUCTIVE_GIT,
    "git checkout -f *": DENY_DESTRUCTIVE_GIT,
    "git checkout --force": DENY_DESTRUCTIVE_GIT,
    "git checkout --force *": DENY_DESTRUCTIVE_GIT,
    "git restore --worktree": DENY_DESTRUCTIVE_GIT,
    "git restore --worktree *": DENY_DESTRUCTIVE_GIT,
    "git push": "ask",
    "git push *": "ask",
    "git commit": "ask",
    "git commit *": "ask",
  },
  ...HARNESS_ALWAYS_ALLOW_PERMISSION,
} as const;
